package main

// var playMoviesList []map[string]interface{}

var playMoviesList = []map[string]interface{}{
	{
		"movie_id":     "934",
		"imdb_id":      "tt4154664",
		"title":        "Captain Marvel",
		"genre":        "Action, Adventure",
		"language":     "English",
		"director":     "Anna Boden, Ryan Fleck",
		"producer":     "Victoria Alonso",
		"release_date": "2019-03-08",
		"cast":         "Brie Larson",
		"ranking":      "6.0",
		"length":       "124",
		"thumbnail":    "https://bookme.pk/custom/upload/marvil_IMDB.jpg"},
	{
		"movie_id":     "901",
		"imdb_id":      "",
		"title":        "3 BAHADUR",
		"genre":        "Adventure,  Animation, Family",
		"language":     "Urdu",
		"director":     "Sharmeen Obaid Chinoy",
		"producer":     "Waadi Animations",
		"release_date": "2018-12-14",
		"cast":         " Mehwish HayatFahad MustafaSarwat GillaniNimra BuchaBehroze Sabzwari",
		"ranking":      "0.9",
		"length":       "120",
		"thumbnail":    "https://bookme.pk/custom/upload/3_Bahadur_RiseWarriors_IMDB.jpeg"}}

var playMovieShowsList = []map[string]interface{}{
	{
		"movie_id":       "942",
		"imdb_id":        "tt5897108",
		"title":          "Project Ghazi",
		"genre":          "Action, Thriller, Sci-Fi",
		"language":       "Urdu",
		"director":       "Nadir Shah",
		"producer":       "Syed Mohammad Ali Raza",
		"release_date":   "2019-03-22",
		"cast":           "Humayun Saeed, Sheheryar Munawar Siddiqui, Syra Shehroz, Adnan Jaffar",
		"ranking":        "8.0",
		"length":         "120",
		"thumbnail":      "https://bookme.pk/custom/upload/PG_IMDB.jpg",
		"music_director": "-",
		"country":        "Pakistan",
		"synopsis":       "Project Ghazi is a superhero movie that evolves around a thread to the project soldiers. Its a story of an advanced soldier project and it spans over a period of 20 years.",
		"details":        "",
		"trailer_link":   "https://bookme.pk/custom/videoupload/PG_Trailer.mp4",
		"date":           "2019-03-08 19:56:33",
		"booking_type":   "0",
		"points":         "0",
		"update_date":    nil,
		"close_date":     nil,
		"status":         "1",
		"shows": []map[string]interface{}{
			{"city_id": "1",
				"city_name":         "Lahore",
				"show_id":           "481862",
				"show_movie_id":     "942",
				"show_cenima_id":    "8888",
				"cinema_name":       "Universal Cinema lahore Emporium Mall",
				"hall_id":           "148",
				"hall_name":         "Screen 3 ",
				"show_date":         "2019-03-29",
				"show_start_time":   "2019-03-29 16:00:00",
				"show_time":         "16:00",
				"ticket_price":      "600",
				"handling_charges":  30,
				"easypaisa_charges": 0,
				"house_full":        "0",
				"eticket":           "1"},
			{"city_id": "2",
				"city_name":         "Karachi",
				"show_id":           "481856",
				"show_movie_id":     "942",
				"show_cenima_id":    "19",
				"cinema_name":       "Atrium Cinema",
				"hall_id":           "62",
				"hall_name":         "Cinema A 2D ",
				"show_date":         "2019-03-30",
				"show_start_time":   "2019-03-30 15:00:00",
				"show_time":         "15:00",
				"ticket_price":      "600",
				"handling_charges":  30,
				"easypaisa_charges": 0,
				"house_full":        "0",
				"eticket":           "1"},
			{"city_id": "3",
				"city_name":         "Islamabad",
				"show_id":           "481858",
				"show_movie_id":     "942",
				"show_cenima_id":    "20",
				"cinema_name":       "Centaurus Cineplex",
				"hall_id":           "68",
				"hall_name":         "Cinema 1 2D ",
				"show_date":         "2019-03-30",
				"show_start_time":   "2019-03-30 14:00:00",
				"show_time":         "14:00",
				"ticket_price":      "600",
				"handling_charges":  30,
				"easypaisa_charges": 0,
				"house_full":        "0",
				"eticket":           "1"}}},

	{
		"movie_id":       "824",
		"imdb_id":        "tt4912910",
		"title":          "Mission Impossible Fallout",
		"genre":          "Action, Thriller, Adventure",
		"language":       "English",
		"director":       "Christopher McQuarrie",
		"producer":       "Tom Cruise",
		"release_date":   "2018-07-27",
		"cast":           "Tom Cruise,Rebecca Ferguson,Henry Cavill",
		"ranking":        "7.8",
		"length":         "227",
		"thumbnail":      "https://bookme.pk/custom/upload/mif_IMDB.jpg",
		"music_director": "Lorne Balfe",
		"country":        "USA",
		"synopsis":       "Ethan Hunt and his IMF team, along with some familiar allies, race against time after a mission gone wrong.",
		"details":        "",
		"trailer_link":   "https://bookme.pk/custom/videoupload/MIF_Trailer.mp4",
		"date":           "2019-03-01 18:58:29",
		"booking_type":   "0",
		"points":         "0",
		"update_date":    "2018-07-23 20:28:37",
		"close_date":     nil,
		"status":         "1",
		"shows": []map[string]interface{}{
			{
				"city_id":           "1",
				"city_name":         "Lahore",
				"show_id":           "480889",
				"show_movie_id":     "824",
				"show_cenima_id":    "8888",
				"cinema_name":       "Universal Cinema lahore Emporium Mall",
				"hall_id":           "149",
				"hall_name":         "Screen 4 Premium B",
				"show_date":         "2019-03-10",
				"show_start_time":   "2019-03-10 17:30:00",
				"show_time":         "17:30",
				"ticket_price":      "700",
				"handling_charges":  35,
				"easypaisa_charges": 0,
				"house_full":        "0",
				"eticket":           "1"},
			{
				"city_id":           "11",
				"city_name":         "Rawalpindi",
				"show_id":           "480788",
				"show_movie_id":     "824",
				"show_cenima_id":    "10009",
				"cinema_name":       "Odeon Cineplex",
				"hall_id":           "203",
				"hall_name":         "Red Hall Vip Box",
				"show_date":         "2019-03-10",
				"show_start_time":   "2019-03-10 19:45:00",
				"show_time":         "19:45",
				"ticket_price":      "3000",
				"handling_charges":  150,
				"easypaisa_charges": 0,
				"house_full":        "0",
				"eticket":           ""}}}}

var CinemaSeatPlanMock = []map[string]interface{}{
	{
		"show_id":   "481856",
		"hall_id":   "62",
		"hall_name": "Cinema A 2D",
		"rows":      "11",
		"cols":      "16",
		"seat_plan": []map[string]interface{}{
			{
				"row":   "A",
				"place": "",
				"seats": []map[string]interface{}{
					{
						"seat_id":       "A_1",
						"seat_row_name": "A",
						"seat_number":   "1",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "A_1",
						"seat_row_name": "A",
						"seat_number":   "1",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "A_1",
						"seat_row_name": "A",
						"seat_number":   "1",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "A_2",
						"seat_row_name": "A",
						"seat_number":   "2",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "A_2",
						"seat_row_name": "A",
						"seat_number":   "2",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "A_2",
						"seat_row_name": "A",
						"seat_number":   "2",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "A_3",
						"seat_row_name": "A",
						"seat_number":   "3",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "A_3",
						"seat_row_name": "A",
						"seat_number":   "3",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "A_3",
						"seat_row_name": "A",
						"seat_number":   "3",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "A_4",
						"seat_row_name": "A",
						"seat_number":   "4",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "A_4",
						"seat_row_name": "A",
						"seat_number":   "4",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "A_4",
						"seat_row_name": "A",
						"seat_number":   "4",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "A_5",
						"seat_row_name": "A",
						"seat_number":   "5",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "A_5",
						"seat_row_name": "A",
						"seat_number":   "5",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "A_5",
						"seat_row_name": "A",
						"seat_number":   "5",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "A_6",
						"seat_row_name": "A",
						"seat_number":   "6",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "A_6",
						"seat_row_name": "A",
						"seat_number":   "6",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "A_6",
						"seat_row_name": "A",
						"seat_number":   "6",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "A_7",
						"seat_row_name": "A",
						"seat_number":   "7",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "A_7",
						"seat_row_name": "A",
						"seat_number":   "7",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "A_7",
						"seat_row_name": "A",
						"seat_number":   "7",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "A_0",
						"seat_row_name": "A",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "A_0",
						"seat_row_name": "A",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "A_0",
						"seat_row_name": "A",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "A_0",
						"seat_row_name": "A",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "A_0",
						"seat_row_name": "A",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "A_0",
						"seat_row_name": "A",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "A_8",
						"seat_row_name": "A",
						"seat_number":   "8",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "A_8",
						"seat_row_name": "A",
						"seat_number":   "8",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "A_8",
						"seat_row_name": "A",
						"seat_number":   "8",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "A_9",
						"seat_row_name": "A",
						"seat_number":   "9",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "A_9",
						"seat_row_name": "A",
						"seat_number":   "9",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "A_9",
						"seat_row_name": "A",
						"seat_number":   "9",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "A_10",
						"seat_row_name": "A",
						"seat_number":   "10",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "A_10",
						"seat_row_name": "A",
						"seat_number":   "10",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "A_10",
						"seat_row_name": "A",
						"seat_number":   "10",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "A_11",
						"seat_row_name": "A",
						"seat_number":   "11",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "A_11",
						"seat_row_name": "A",
						"seat_number":   "11",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "A_11",
						"seat_row_name": "A",
						"seat_number":   "11",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "A_12",
						"seat_row_name": "A",
						"seat_number":   "12",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "A_12",
						"seat_row_name": "A",
						"seat_number":   "12",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "A_12",
						"seat_row_name": "A",
						"seat_number":   "12",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "A_13",
						"seat_row_name": "A",
						"seat_number":   "13",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "A_13",
						"seat_row_name": "A",
						"seat_number":   "13",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "A_13",
						"seat_row_name": "A",
						"seat_number":   "13",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "A_14",
						"seat_row_name": "A",
						"seat_number":   "14",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "A_14",
						"seat_row_name": "A",
						"seat_number":   "14",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "A_14",
						"seat_row_name": "A",
						"seat_number":   "14",
						"seat_type":     "1",
						"status":        0}}},
			{
				"row":   "B",
				"place": "",
				"seats": []map[string]interface{}{
					{
						"seat_id":       "B_1",
						"seat_row_name": "B",
						"seat_number":   "1",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "B_1",
						"seat_row_name": "B",
						"seat_number":   "1",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "B_1",
						"seat_row_name": "B",
						"seat_number":   "1",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "B_2",
						"seat_row_name": "B",
						"seat_number":   "2",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "B_2",
						"seat_row_name": "B",
						"seat_number":   "2",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "B_2",
						"seat_row_name": "B",
						"seat_number":   "2",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "B_3",
						"seat_row_name": "B",
						"seat_number":   "3",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "B_3",
						"seat_row_name": "B",
						"seat_number":   "3",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "B_3",
						"seat_row_name": "B",
						"seat_number":   "3",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "B_4",
						"seat_row_name": "B",
						"seat_number":   "4",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "B_4",
						"seat_row_name": "B",
						"seat_number":   "4",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "B_4",
						"seat_row_name": "B",
						"seat_number":   "4",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "B_5",
						"seat_row_name": "B",
						"seat_number":   "5",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "B_5",
						"seat_row_name": "B",
						"seat_number":   "5",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "B_5",
						"seat_row_name": "B",
						"seat_number":   "5",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "B_6",
						"seat_row_name": "B",
						"seat_number":   "6",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "B_6",
						"seat_row_name": "B",
						"seat_number":   "6",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "B_6",
						"seat_row_name": "B",
						"seat_number":   "6",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "B_7",
						"seat_row_name": "B",
						"seat_number":   "7",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "B_7",
						"seat_row_name": "B",
						"seat_number":   "7",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "B_7",
						"seat_row_name": "B",
						"seat_number":   "7",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "B_0",
						"seat_row_name": "B",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "B_0",
						"seat_row_name": "B",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "B_0",
						"seat_row_name": "B",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "B_0",
						"seat_row_name": "B",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "B_0",
						"seat_row_name": "B",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "B_0",
						"seat_row_name": "B",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "B_8",
						"seat_row_name": "B",
						"seat_number":   "8",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "B_8",
						"seat_row_name": "B",
						"seat_number":   "8",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "B_8",
						"seat_row_name": "B",
						"seat_number":   "8",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "B_9",
						"seat_row_name": "B",
						"seat_number":   "9",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "B_9",
						"seat_row_name": "B",
						"seat_number":   "9",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "B_9",
						"seat_row_name": "B",
						"seat_number":   "9",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "B_10",
						"seat_row_name": "B",
						"seat_number":   "10",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "B_10",
						"seat_row_name": "B",
						"seat_number":   "10",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "B_10",
						"seat_row_name": "B",
						"seat_number":   "10",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "B_11",
						"seat_row_name": "B",
						"seat_number":   "11",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "B_11",
						"seat_row_name": "B",
						"seat_number":   "11",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "B_11",
						"seat_row_name": "B",
						"seat_number":   "11",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "B_12",
						"seat_row_name": "B",
						"seat_number":   "12",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "B_12",
						"seat_row_name": "B",
						"seat_number":   "12",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "B_12",
						"seat_row_name": "B",
						"seat_number":   "12",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "B_13",
						"seat_row_name": "B",
						"seat_number":   "13",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "B_13",
						"seat_row_name": "B",
						"seat_number":   "13",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "B_13",
						"seat_row_name": "B",
						"seat_number":   "13",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "B_14",
						"seat_row_name": "B",
						"seat_number":   "14",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "B_14",
						"seat_row_name": "B",
						"seat_number":   "14",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "B_14",
						"seat_row_name": "B",
						"seat_number":   "14",
						"seat_type":     "1",
						"status":        0}}},
			{
				"row":   "C",
				"place": "",
				"seats": []map[string]interface{}{
					{
						"seat_id":       "C_1",
						"seat_row_name": "C",
						"seat_number":   "1",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "C_1",
						"seat_row_name": "C",
						"seat_number":   "1",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "C_1",
						"seat_row_name": "C",
						"seat_number":   "1",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "C_2",
						"seat_row_name": "C",
						"seat_number":   "2",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "C_2",
						"seat_row_name": "C",
						"seat_number":   "2",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "C_2",
						"seat_row_name": "C",
						"seat_number":   "2",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "C_3",
						"seat_row_name": "C",
						"seat_number":   "3",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "C_3",
						"seat_row_name": "C",
						"seat_number":   "3",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "C_3",
						"seat_row_name": "C",
						"seat_number":   "3",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "C_4",
						"seat_row_name": "C",
						"seat_number":   "4",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "C_4",
						"seat_row_name": "C",
						"seat_number":   "4",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "C_4",
						"seat_row_name": "C",
						"seat_number":   "4",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "C_5",
						"seat_row_name": "C",
						"seat_number":   "5",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "C_5",
						"seat_row_name": "C",
						"seat_number":   "5",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "C_5",
						"seat_row_name": "C",
						"seat_number":   "5",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "C_6",
						"seat_row_name": "C",
						"seat_number":   "6",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "C_6",
						"seat_row_name": "C",
						"seat_number":   "6",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "C_6",
						"seat_row_name": "C",
						"seat_number":   "6",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "C_7",
						"seat_row_name": "C",
						"seat_number":   "7",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "C_7",
						"seat_row_name": "C",
						"seat_number":   "7",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "C_7",
						"seat_row_name": "C",
						"seat_number":   "7",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "C_0",
						"seat_row_name": "C",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "C_0",
						"seat_row_name": "C",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "C_0",
						"seat_row_name": "C",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "C_0",
						"seat_row_name": "C",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "C_0",
						"seat_row_name": "C",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "C_0",
						"seat_row_name": "C",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "C_8",
						"seat_row_name": "C",
						"seat_number":   "8",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "C_8",
						"seat_row_name": "C",
						"seat_number":   "8",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "C_8",
						"seat_row_name": "C",
						"seat_number":   "8",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "C_9",
						"seat_row_name": "C",
						"seat_number":   "9",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "C_9",
						"seat_row_name": "C",
						"seat_number":   "9",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "C_9",
						"seat_row_name": "C",
						"seat_number":   "9",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "C_10",
						"seat_row_name": "C",
						"seat_number":   "10",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "C_10",
						"seat_row_name": "C",
						"seat_number":   "10",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "C_10",
						"seat_row_name": "C",
						"seat_number":   "10",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "C_11",
						"seat_row_name": "C",
						"seat_number":   "11",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "C_11",
						"seat_row_name": "C",
						"seat_number":   "11",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "C_11",
						"seat_row_name": "C",
						"seat_number":   "11",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "C_12",
						"seat_row_name": "C",
						"seat_number":   "12",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "C_12",
						"seat_row_name": "C",
						"seat_number":   "12",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "C_12",
						"seat_row_name": "C",
						"seat_number":   "12",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "C_13",
						"seat_row_name": "C",
						"seat_number":   "13",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "C_13",
						"seat_row_name": "C",
						"seat_number":   "13",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "C_13",
						"seat_row_name": "C",
						"seat_number":   "13",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "C_14",
						"seat_row_name": "C",
						"seat_number":   "14",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "C_14",
						"seat_row_name": "C",
						"seat_number":   "14",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "C_14",
						"seat_row_name": "C",
						"seat_number":   "14",
						"seat_type":     "1",
						"status":        0}}},
			{
				"row":   "D",
				"place": "",
				"seats": []map[string]interface{}{
					{
						"seat_id":       "D_1",
						"seat_row_name": "D",
						"seat_number":   "1",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "D_1",
						"seat_row_name": "D",
						"seat_number":   "1",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "D_1",
						"seat_row_name": "D",
						"seat_number":   "1",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "D_2",
						"seat_row_name": "D",
						"seat_number":   "2",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "D_2",
						"seat_row_name": "D",
						"seat_number":   "2",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "D_2",
						"seat_row_name": "D",
						"seat_number":   "2",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "D_3",
						"seat_row_name": "D",
						"seat_number":   "3",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "D_3",
						"seat_row_name": "D",
						"seat_number":   "3",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "D_3",
						"seat_row_name": "D",
						"seat_number":   "3",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "D_4",
						"seat_row_name": "D",
						"seat_number":   "4",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "D_4",
						"seat_row_name": "D",
						"seat_number":   "4",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "D_4",
						"seat_row_name": "D",
						"seat_number":   "4",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "D_5",
						"seat_row_name": "D",
						"seat_number":   "5",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "D_5",
						"seat_row_name": "D",
						"seat_number":   "5",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "D_5",
						"seat_row_name": "D",
						"seat_number":   "5",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "D_6",
						"seat_row_name": "D",
						"seat_number":   "6",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "D_6",
						"seat_row_name": "D",
						"seat_number":   "6",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "D_6",
						"seat_row_name": "D",
						"seat_number":   "6",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "D_7",
						"seat_row_name": "D",
						"seat_number":   "7",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "D_7",
						"seat_row_name": "D",
						"seat_number":   "7",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "D_7",
						"seat_row_name": "D",
						"seat_number":   "7",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "D_0",
						"seat_row_name": "D",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "D_0",
						"seat_row_name": "D",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "D_0",
						"seat_row_name": "D",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "D_0",
						"seat_row_name": "D",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "D_0",
						"seat_row_name": "D",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "D_0",
						"seat_row_name": "D",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "D_8",
						"seat_row_name": "D",
						"seat_number":   "8",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "D_8",
						"seat_row_name": "D",
						"seat_number":   "8",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "D_8",
						"seat_row_name": "D",
						"seat_number":   "8",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "D_9",
						"seat_row_name": "D",
						"seat_number":   "9",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "D_9",
						"seat_row_name": "D",
						"seat_number":   "9",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "D_9",
						"seat_row_name": "D",
						"seat_number":   "9",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "D_10",
						"seat_row_name": "D",
						"seat_number":   "10",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "D_10",
						"seat_row_name": "D",
						"seat_number":   "10",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "D_10",
						"seat_row_name": "D",
						"seat_number":   "10",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "D_11",
						"seat_row_name": "D",
						"seat_number":   "11",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "D_11",
						"seat_row_name": "D",
						"seat_number":   "11",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "D_11",
						"seat_row_name": "D",
						"seat_number":   "11",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "D_12",
						"seat_row_name": "D",
						"seat_number":   "12",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "D_12",
						"seat_row_name": "D",
						"seat_number":   "12",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "D_12",
						"seat_row_name": "D",
						"seat_number":   "12",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "D_13",
						"seat_row_name": "D",
						"seat_number":   "13",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "D_13",
						"seat_row_name": "D",
						"seat_number":   "13",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "D_13",
						"seat_row_name": "D",
						"seat_number":   "13",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "D_14",
						"seat_row_name": "D",
						"seat_number":   "14",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "D_14",
						"seat_row_name": "D",
						"seat_number":   "14",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "D_14",
						"seat_row_name": "D",
						"seat_number":   "14",
						"seat_type":     "1",
						"status":        0}}},
			{
				"row":   "E",
				"place": "",
				"seats": []map[string]interface{}{
					{
						"seat_id":       "E_1",
						"seat_row_name": "E",
						"seat_number":   "1",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "E_1",
						"seat_row_name": "E",
						"seat_number":   "1",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "E_1",
						"seat_row_name": "E",
						"seat_number":   "1",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "E_2",
						"seat_row_name": "E",
						"seat_number":   "2",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "E_2",
						"seat_row_name": "E",
						"seat_number":   "2",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "E_2",
						"seat_row_name": "E",
						"seat_number":   "2",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "E_3",
						"seat_row_name": "E",
						"seat_number":   "3",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "E_3",
						"seat_row_name": "E",
						"seat_number":   "3",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "E_3",
						"seat_row_name": "E",
						"seat_number":   "3",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "E_4",
						"seat_row_name": "E",
						"seat_number":   "4",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "E_4",
						"seat_row_name": "E",
						"seat_number":   "4",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "E_4",
						"seat_row_name": "E",
						"seat_number":   "4",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "E_5",
						"seat_row_name": "E",
						"seat_number":   "5",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "E_5",
						"seat_row_name": "E",
						"seat_number":   "5",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "E_5",
						"seat_row_name": "E",
						"seat_number":   "5",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "E_6",
						"seat_row_name": "E",
						"seat_number":   "6",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "E_6",
						"seat_row_name": "E",
						"seat_number":   "6",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "E_6",
						"seat_row_name": "E",
						"seat_number":   "6",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "E_7",
						"seat_row_name": "E",
						"seat_number":   "7",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "E_7",
						"seat_row_name": "E",
						"seat_number":   "7",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "E_7",
						"seat_row_name": "E",
						"seat_number":   "7",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "E_0",
						"seat_row_name": "E",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "E_0",
						"seat_row_name": "E",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "E_0",
						"seat_row_name": "E",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "E_0",
						"seat_row_name": "E",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "E_0",
						"seat_row_name": "E",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "E_0",
						"seat_row_name": "E",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "E_8",
						"seat_row_name": "E",
						"seat_number":   "8",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "E_8",
						"seat_row_name": "E",
						"seat_number":   "8",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "E_8",
						"seat_row_name": "E",
						"seat_number":   "8",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "E_9",
						"seat_row_name": "E",
						"seat_number":   "9",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "E_9",
						"seat_row_name": "E",
						"seat_number":   "9",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "E_9",
						"seat_row_name": "E",
						"seat_number":   "9",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "E_10",
						"seat_row_name": "E",
						"seat_number":   "10",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "E_10",
						"seat_row_name": "E",
						"seat_number":   "10",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "E_10",
						"seat_row_name": "E",
						"seat_number":   "10",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "E_11",
						"seat_row_name": "E",
						"seat_number":   "11",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "E_11",
						"seat_row_name": "E",
						"seat_number":   "11",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "E_11",
						"seat_row_name": "E",
						"seat_number":   "11",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "E_12",
						"seat_row_name": "E",
						"seat_number":   "12",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "E_12",
						"seat_row_name": "E",
						"seat_number":   "12",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "E_12",
						"seat_row_name": "E",
						"seat_number":   "12",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "E_13",
						"seat_row_name": "E",
						"seat_number":   "13",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "E_13",
						"seat_row_name": "E",
						"seat_number":   "13",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "E_13",
						"seat_row_name": "E",
						"seat_number":   "13",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "E_14",
						"seat_row_name": "E",
						"seat_number":   "14",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "E_14",
						"seat_row_name": "E",
						"seat_number":   "14",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "E_14",
						"seat_row_name": "E",
						"seat_number":   "14",
						"seat_type":     "1",
						"status":        0}}},
			{
				"row":   "F",
				"place": "",
				"seats": []map[string]interface{}{
					{
						"seat_id":       "F_1",
						"seat_row_name": "F",
						"seat_number":   "1",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "F_1",
						"seat_row_name": "F",
						"seat_number":   "1",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "F_1",
						"seat_row_name": "F",
						"seat_number":   "1",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "F_2",
						"seat_row_name": "F",
						"seat_number":   "2",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "F_2",
						"seat_row_name": "F",
						"seat_number":   "2",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "F_2",
						"seat_row_name": "F",
						"seat_number":   "2",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "F_3",
						"seat_row_name": "F",
						"seat_number":   "3",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "F_3",
						"seat_row_name": "F",
						"seat_number":   "3",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "F_3",
						"seat_row_name": "F",
						"seat_number":   "3",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "F_4",
						"seat_row_name": "F",
						"seat_number":   "4",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "F_4",
						"seat_row_name": "F",
						"seat_number":   "4",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "F_4",
						"seat_row_name": "F",
						"seat_number":   "4",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "F_5",
						"seat_row_name": "F",
						"seat_number":   "5",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "F_5",
						"seat_row_name": "F",
						"seat_number":   "5",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "F_5",
						"seat_row_name": "F",
						"seat_number":   "5",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "F_6",
						"seat_row_name": "F",
						"seat_number":   "6",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "F_6",
						"seat_row_name": "F",
						"seat_number":   "6",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "F_6",
						"seat_row_name": "F",
						"seat_number":   "6",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "F_7",
						"seat_row_name": "F",
						"seat_number":   "7",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "F_7",
						"seat_row_name": "F",
						"seat_number":   "7",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "F_7",
						"seat_row_name": "F",
						"seat_number":   "7",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "F_0",
						"seat_row_name": "F",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "F_0",
						"seat_row_name": "F",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "F_0",
						"seat_row_name": "F",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "F_0",
						"seat_row_name": "F",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "F_0",
						"seat_row_name": "F",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "F_0",
						"seat_row_name": "F",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "F_8",
						"seat_row_name": "F",
						"seat_number":   "8",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "F_8",
						"seat_row_name": "F",
						"seat_number":   "8",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "F_8",
						"seat_row_name": "F",
						"seat_number":   "8",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "F_9",
						"seat_row_name": "F",
						"seat_number":   "9",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "F_9",
						"seat_row_name": "F",
						"seat_number":   "9",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "F_9",
						"seat_row_name": "F",
						"seat_number":   "9",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "F_10",
						"seat_row_name": "F",
						"seat_number":   "10",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "F_10",
						"seat_row_name": "F",
						"seat_number":   "10",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "F_10",
						"seat_row_name": "F",
						"seat_number":   "10",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "F_11",
						"seat_row_name": "F",
						"seat_number":   "11",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "F_11",
						"seat_row_name": "F",
						"seat_number":   "11",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "F_11",
						"seat_row_name": "F",
						"seat_number":   "11",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "F_12",
						"seat_row_name": "F",
						"seat_number":   "12",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "F_12",
						"seat_row_name": "F",
						"seat_number":   "12",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "F_12",
						"seat_row_name": "F",
						"seat_number":   "12",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "F_13",
						"seat_row_name": "F",
						"seat_number":   "13",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "F_13",
						"seat_row_name": "F",
						"seat_number":   "13",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "F_13",
						"seat_row_name": "F",
						"seat_number":   "13",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "F_14",
						"seat_row_name": "F",
						"seat_number":   "14",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "F_14",
						"seat_row_name": "F",
						"seat_number":   "14",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "F_14",
						"seat_row_name": "F",
						"seat_number":   "14",
						"seat_type":     "1",
						"status":        0}}},
			{
				"row":   "G",
				"place": "",
				"seats": []map[string]interface{}{
					{
						"seat_id":       "G_1",
						"seat_row_name": "G",
						"seat_number":   "1",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "G_1",
						"seat_row_name": "G",
						"seat_number":   "1",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "G_1",
						"seat_row_name": "G",
						"seat_number":   "1",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "G_2",
						"seat_row_name": "G",
						"seat_number":   "2",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "G_2",
						"seat_row_name": "G",
						"seat_number":   "2",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "G_2",
						"seat_row_name": "G",
						"seat_number":   "2",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "G_3",
						"seat_row_name": "G",
						"seat_number":   "3",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "G_3",
						"seat_row_name": "G",
						"seat_number":   "3",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "G_3",
						"seat_row_name": "G",
						"seat_number":   "3",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "G_4",
						"seat_row_name": "G",
						"seat_number":   "4",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "G_4",
						"seat_row_name": "G",
						"seat_number":   "4",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "G_4",
						"seat_row_name": "G",
						"seat_number":   "4",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "G_5",
						"seat_row_name": "G",
						"seat_number":   "5",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "G_5",
						"seat_row_name": "G",
						"seat_number":   "5",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "G_5",
						"seat_row_name": "G",
						"seat_number":   "5",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "G_6",
						"seat_row_name": "G",
						"seat_number":   "6",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "G_6",
						"seat_row_name": "G",
						"seat_number":   "6",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "G_6",
						"seat_row_name": "G",
						"seat_number":   "6",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "G_7",
						"seat_row_name": "G",
						"seat_number":   "7",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "G_7",
						"seat_row_name": "G",
						"seat_number":   "7",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "G_7",
						"seat_row_name": "G",
						"seat_number":   "7",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "G_0",
						"seat_row_name": "G",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "G_0",
						"seat_row_name": "G",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "G_0",
						"seat_row_name": "G",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "G_0",
						"seat_row_name": "G",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "G_0",
						"seat_row_name": "G",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "G_0",
						"seat_row_name": "G",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "G_8",
						"seat_row_name": "G",
						"seat_number":   "8",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "G_8",
						"seat_row_name": "G",
						"seat_number":   "8",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "G_8",
						"seat_row_name": "G",
						"seat_number":   "8",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "G_9",
						"seat_row_name": "G",
						"seat_number":   "9",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "G_9",
						"seat_row_name": "G",
						"seat_number":   "9",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "G_9",
						"seat_row_name": "G",
						"seat_number":   "9",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "G_10",
						"seat_row_name": "G",
						"seat_number":   "10",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "G_10",
						"seat_row_name": "G",
						"seat_number":   "10",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "G_10",
						"seat_row_name": "G",
						"seat_number":   "10",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "G_11",
						"seat_row_name": "G",
						"seat_number":   "11",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "G_11",
						"seat_row_name": "G",
						"seat_number":   "11",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "G_11",
						"seat_row_name": "G",
						"seat_number":   "11",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "G_12",
						"seat_row_name": "G",
						"seat_number":   "12",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "G_12",
						"seat_row_name": "G",
						"seat_number":   "12",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "G_12",
						"seat_row_name": "G",
						"seat_number":   "12",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "G_13",
						"seat_row_name": "G",
						"seat_number":   "13",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "G_13",
						"seat_row_name": "G",
						"seat_number":   "13",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "G_13",
						"seat_row_name": "G",
						"seat_number":   "13",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "G_14",
						"seat_row_name": "G",
						"seat_number":   "14",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "G_14",
						"seat_row_name": "G",
						"seat_number":   "14",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "G_14",
						"seat_row_name": "G",
						"seat_number":   "14",
						"seat_type":     "1",
						"status":        0}}},
			{
				"row":   "H",
				"place": "",
				"seats": []map[string]interface{}{
					{
						"seat_id":       "H_1",
						"seat_row_name": "H",
						"seat_number":   "1",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "H_1",
						"seat_row_name": "H",
						"seat_number":   "1",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "H_1",
						"seat_row_name": "H",
						"seat_number":   "1",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "H_2",
						"seat_row_name": "H",
						"seat_number":   "2",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "H_2",
						"seat_row_name": "H",
						"seat_number":   "2",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "H_2",
						"seat_row_name": "H",
						"seat_number":   "2",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "H_3",
						"seat_row_name": "H",
						"seat_number":   "3",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "H_3",
						"seat_row_name": "H",
						"seat_number":   "3",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "H_3",
						"seat_row_name": "H",
						"seat_number":   "3",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "H_4",
						"seat_row_name": "H",
						"seat_number":   "4",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "H_4",
						"seat_row_name": "H",
						"seat_number":   "4",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "H_4",
						"seat_row_name": "H",
						"seat_number":   "4",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "H_5",
						"seat_row_name": "H",
						"seat_number":   "5",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "H_5",
						"seat_row_name": "H",
						"seat_number":   "5",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "H_5",
						"seat_row_name": "H",
						"seat_number":   "5",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "H_6",
						"seat_row_name": "H",
						"seat_number":   "6",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "H_6",
						"seat_row_name": "H",
						"seat_number":   "6",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "H_6",
						"seat_row_name": "H",
						"seat_number":   "6",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "H_7",
						"seat_row_name": "H",
						"seat_number":   "7",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "H_7",
						"seat_row_name": "H",
						"seat_number":   "7",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "H_7",
						"seat_row_name": "H",
						"seat_number":   "7",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "H_0",
						"seat_row_name": "H",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "H_0",
						"seat_row_name": "H",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "H_0",
						"seat_row_name": "H",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "H_0",
						"seat_row_name": "H",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "H_0",
						"seat_row_name": "H",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "H_0",
						"seat_row_name": "H",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "H_8",
						"seat_row_name": "H",
						"seat_number":   "8",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "H_8",
						"seat_row_name": "H",
						"seat_number":   "8",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "H_8",
						"seat_row_name": "H",
						"seat_number":   "8",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "H_9",
						"seat_row_name": "H",
						"seat_number":   "9",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "H_9",
						"seat_row_name": "H",
						"seat_number":   "9",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "H_9",
						"seat_row_name": "H",
						"seat_number":   "9",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "H_10",
						"seat_row_name": "H",
						"seat_number":   "10",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "H_10",
						"seat_row_name": "H",
						"seat_number":   "10",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "H_10",
						"seat_row_name": "H",
						"seat_number":   "10",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "H_11",
						"seat_row_name": "H",
						"seat_number":   "11",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "H_11",
						"seat_row_name": "H",
						"seat_number":   "11",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "H_11",
						"seat_row_name": "H",
						"seat_number":   "11",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "H_12",
						"seat_row_name": "H",
						"seat_number":   "12",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "H_12",
						"seat_row_name": "H",
						"seat_number":   "12",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "H_12",
						"seat_row_name": "H",
						"seat_number":   "12",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "H_13",
						"seat_row_name": "H",
						"seat_number":   "13",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "H_13",
						"seat_row_name": "H",
						"seat_number":   "13",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "H_13",
						"seat_row_name": "H",
						"seat_number":   "13",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "H_14",
						"seat_row_name": "H",
						"seat_number":   "14",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "H_14",
						"seat_row_name": "H",
						"seat_number":   "14",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "H_14",
						"seat_row_name": "H",
						"seat_number":   "14",
						"seat_type":     "1",
						"status":        0}}},
			{
				"row":   "I",
				"place": "",
				"seats": []map[string]interface{}{
					{
						"seat_id":       "I_1",
						"seat_row_name": "I",
						"seat_number":   "1",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "I_1",
						"seat_row_name": "I",
						"seat_number":   "1",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "I_1",
						"seat_row_name": "I",
						"seat_number":   "1",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "I_2",
						"seat_row_name": "I",
						"seat_number":   "2",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "I_2",
						"seat_row_name": "I",
						"seat_number":   "2",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "I_2",
						"seat_row_name": "I",
						"seat_number":   "2",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "I_3",
						"seat_row_name": "I",
						"seat_number":   "3",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "I_3",
						"seat_row_name": "I",
						"seat_number":   "3",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "I_3",
						"seat_row_name": "I",
						"seat_number":   "3",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "I_4",
						"seat_row_name": "I",
						"seat_number":   "4",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "I_4",
						"seat_row_name": "I",
						"seat_number":   "4",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "I_4",
						"seat_row_name": "I",
						"seat_number":   "4",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "I_5",
						"seat_row_name": "I",
						"seat_number":   "5",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "I_5",
						"seat_row_name": "I",
						"seat_number":   "5",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "I_5",
						"seat_row_name": "I",
						"seat_number":   "5",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "I_6",
						"seat_row_name": "I",
						"seat_number":   "6",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "I_6",
						"seat_row_name": "I",
						"seat_number":   "6",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "I_6",
						"seat_row_name": "I",
						"seat_number":   "6",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "I_7",
						"seat_row_name": "I",
						"seat_number":   "7",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "I_7",
						"seat_row_name": "I",
						"seat_number":   "7",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "I_7",
						"seat_row_name": "I",
						"seat_number":   "7",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "I_0",
						"seat_row_name": "I",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "I_0",
						"seat_row_name": "I",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "I_0",
						"seat_row_name": "I",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "I_0",
						"seat_row_name": "I",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "I_0",
						"seat_row_name": "I",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "I_0",
						"seat_row_name": "I",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "I_8",
						"seat_row_name": "I",
						"seat_number":   "8",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "I_8",
						"seat_row_name": "I",
						"seat_number":   "8",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "I_8",
						"seat_row_name": "I",
						"seat_number":   "8",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "I_9",
						"seat_row_name": "I",
						"seat_number":   "9",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "I_9",
						"seat_row_name": "I",
						"seat_number":   "9",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "I_9",
						"seat_row_name": "I",
						"seat_number":   "9",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "I_10",
						"seat_row_name": "I",
						"seat_number":   "10",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "I_10",
						"seat_row_name": "I",
						"seat_number":   "10",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "I_10",
						"seat_row_name": "I",
						"seat_number":   "10",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "I_11",
						"seat_row_name": "I",
						"seat_number":   "11",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "I_11",
						"seat_row_name": "I",
						"seat_number":   "11",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "I_11",
						"seat_row_name": "I",
						"seat_number":   "11",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "I_12",
						"seat_row_name": "I",
						"seat_number":   "12",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "I_12",
						"seat_row_name": "I",
						"seat_number":   "12",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "I_12",
						"seat_row_name": "I",
						"seat_number":   "12",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "I_13",
						"seat_row_name": "I",
						"seat_number":   "13",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "I_13",
						"seat_row_name": "I",
						"seat_number":   "13",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "I_13",
						"seat_row_name": "I",
						"seat_number":   "13",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "I_14",
						"seat_row_name": "I",
						"seat_number":   "14",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "I_14",
						"seat_row_name": "I",
						"seat_number":   "14",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "I_14",
						"seat_row_name": "I",
						"seat_number":   "14",
						"seat_type":     "1",
						"status":        0}}},
			{
				"row":   "J",
				"place": "",
				"seats": []map[string]interface{}{
					{
						"seat_id":       "J_1",
						"seat_row_name": "J",
						"seat_number":   "1",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "J_1",
						"seat_row_name": "J",
						"seat_number":   "1",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "J_1",
						"seat_row_name": "J",
						"seat_number":   "1",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "J_2",
						"seat_row_name": "J",
						"seat_number":   "2",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "J_2",
						"seat_row_name": "J",
						"seat_number":   "2",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "J_2",
						"seat_row_name": "J",
						"seat_number":   "2",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "J_3",
						"seat_row_name": "J",
						"seat_number":   "3",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "J_3",
						"seat_row_name": "J",
						"seat_number":   "3",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "J_3",
						"seat_row_name": "J",
						"seat_number":   "3",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "J_4",
						"seat_row_name": "J",
						"seat_number":   "4",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "J_4",
						"seat_row_name": "J",
						"seat_number":   "4",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "J_4",
						"seat_row_name": "J",
						"seat_number":   "4",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "J_5",
						"seat_row_name": "J",
						"seat_number":   "5",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "J_5",
						"seat_row_name": "J",
						"seat_number":   "5",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "J_5",
						"seat_row_name": "J",
						"seat_number":   "5",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "J_6",
						"seat_row_name": "J",
						"seat_number":   "6",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "J_6",
						"seat_row_name": "J",
						"seat_number":   "6",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "J_6",
						"seat_row_name": "J",
						"seat_number":   "6",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "J_7",
						"seat_row_name": "J",
						"seat_number":   "7",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "J_7",
						"seat_row_name": "J",
						"seat_number":   "7",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "J_7",
						"seat_row_name": "J",
						"seat_number":   "7",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "J_0",
						"seat_row_name": "J",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "J_0",
						"seat_row_name": "J",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "J_0",
						"seat_row_name": "J",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "J_0",
						"seat_row_name": "J",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "J_0",
						"seat_row_name": "J",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "J_0",
						"seat_row_name": "J",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "J_8",
						"seat_row_name": "J",
						"seat_number":   "8",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "J_8",
						"seat_row_name": "J",
						"seat_number":   "8",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "J_8",
						"seat_row_name": "J",
						"seat_number":   "8",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "J_9",
						"seat_row_name": "J",
						"seat_number":   "9",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "J_9",
						"seat_row_name": "J",
						"seat_number":   "9",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "J_9",
						"seat_row_name": "J",
						"seat_number":   "9",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "J_10",
						"seat_row_name": "J",
						"seat_number":   "10",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "J_10",
						"seat_row_name": "J",
						"seat_number":   "10",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "J_10",
						"seat_row_name": "J",
						"seat_number":   "10",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "J_11",
						"seat_row_name": "J",
						"seat_number":   "11",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "J_11",
						"seat_row_name": "J",
						"seat_number":   "11",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "J_11",
						"seat_row_name": "J",
						"seat_number":   "11",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "J_12",
						"seat_row_name": "J",
						"seat_number":   "12",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "J_12",
						"seat_row_name": "J",
						"seat_number":   "12",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "J_12",
						"seat_row_name": "J",
						"seat_number":   "12",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "J_13",
						"seat_row_name": "J",
						"seat_number":   "13",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "J_13",
						"seat_row_name": "J",
						"seat_number":   "13",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "J_13",
						"seat_row_name": "J",
						"seat_number":   "13",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "J_14",
						"seat_row_name": "J",
						"seat_number":   "14",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "J_14",
						"seat_row_name": "J",
						"seat_number":   "14",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "J_14",
						"seat_row_name": "J",
						"seat_number":   "14",
						"seat_type":     "1",
						"status":        0}}},
			{
				"row":   "K",
				"place": "",
				"seats": []map[string]interface{}{
					{
						"seat_id":       "K_1",
						"seat_row_name": "K",
						"seat_number":   "1",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "K_1",
						"seat_row_name": "K",
						"seat_number":   "1",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "K_1",
						"seat_row_name": "K",
						"seat_number":   "1",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "K_2",
						"seat_row_name": "K",
						"seat_number":   "2",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "K_2",
						"seat_row_name": "K",
						"seat_number":   "2",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "K_2",
						"seat_row_name": "K",
						"seat_number":   "2",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "K_3",
						"seat_row_name": "K",
						"seat_number":   "3",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "K_3",
						"seat_row_name": "K",
						"seat_number":   "3",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "K_3",
						"seat_row_name": "K",
						"seat_number":   "3",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "K_4",
						"seat_row_name": "K",
						"seat_number":   "4",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "K_4",
						"seat_row_name": "K",
						"seat_number":   "4",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "K_4",
						"seat_row_name": "K",
						"seat_number":   "4",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "K_5",
						"seat_row_name": "K",
						"seat_number":   "5",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "K_5",
						"seat_row_name": "K",
						"seat_number":   "5",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "K_5",
						"seat_row_name": "K",
						"seat_number":   "5",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "K_6",
						"seat_row_name": "K",
						"seat_number":   "6",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "K_6",
						"seat_row_name": "K",
						"seat_number":   "6",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "K_6",
						"seat_row_name": "K",
						"seat_number":   "6",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "K_7",
						"seat_row_name": "K",
						"seat_number":   "7",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "K_7",
						"seat_row_name": "K",
						"seat_number":   "7",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "K_7",
						"seat_row_name": "K",
						"seat_number":   "7",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "K_0",
						"seat_row_name": "K",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "K_0",
						"seat_row_name": "K",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "K_0",
						"seat_row_name": "K",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "K_0",
						"seat_row_name": "K",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "K_0",
						"seat_row_name": "K",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "K_0",
						"seat_row_name": "K",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "K_8",
						"seat_row_name": "K",
						"seat_number":   "8",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "K_8",
						"seat_row_name": "K",
						"seat_number":   "8",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "K_8",
						"seat_row_name": "K",
						"seat_number":   "8",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "K_9",
						"seat_row_name": "K",
						"seat_number":   "9",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "K_9",
						"seat_row_name": "K",
						"seat_number":   "9",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "K_9",
						"seat_row_name": "K",
						"seat_number":   "9",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "K_10",
						"seat_row_name": "K",
						"seat_number":   "10",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "K_10",
						"seat_row_name": "K",
						"seat_number":   "10",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "K_10",
						"seat_row_name": "K",
						"seat_number":   "10",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "K_11",
						"seat_row_name": "K",
						"seat_number":   "11",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "K_11",
						"seat_row_name": "K",
						"seat_number":   "11",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "K_11",
						"seat_row_name": "K",
						"seat_number":   "11",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "K_12",
						"seat_row_name": "K",
						"seat_number":   "12",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "K_12",
						"seat_row_name": "K",
						"seat_number":   "12",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "K_12",
						"seat_row_name": "K",
						"seat_number":   "12",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "K_13",
						"seat_row_name": "K",
						"seat_number":   "13",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "K_13",
						"seat_row_name": "K",
						"seat_number":   "13",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "K_13",
						"seat_row_name": "K",
						"seat_number":   "13",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "K_14",
						"seat_row_name": "K",
						"seat_number":   "14",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "K_14",
						"seat_row_name": "K",
						"seat_number":   "14",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "K_14",
						"seat_row_name": "K",
						"seat_number":   "14",
						"seat_type":     "1",
						"status":        0}}},
			{
				"row":   "L",
				"place": "",
				"seats": []map[string]interface{}{
					{
						"seat_id":       "L_1",
						"seat_row_name": "L",
						"seat_number":   "1",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "L_1",
						"seat_row_name": "L",
						"seat_number":   "1",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "L_2",
						"seat_row_name": "L",
						"seat_number":   "2",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "L_2",
						"seat_row_name": "L",
						"seat_number":   "2",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "L_3",
						"seat_row_name": "L",
						"seat_number":   "3",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "L_3",
						"seat_row_name": "L",
						"seat_number":   "3",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "L_4",
						"seat_row_name": "L",
						"seat_number":   "4",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "L_4",
						"seat_row_name": "L",
						"seat_number":   "4",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "L_5",
						"seat_row_name": "L",
						"seat_number":   "5",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "L_5",
						"seat_row_name": "L",
						"seat_number":   "5",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "L_6",
						"seat_row_name": "L",
						"seat_number":   "6",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "L_6",
						"seat_row_name": "L",
						"seat_number":   "6",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "L_7",
						"seat_row_name": "L",
						"seat_number":   "7",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "L_7",
						"seat_row_name": "L",
						"seat_number":   "7",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "L_0",
						"seat_row_name": "L",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "L_0",
						"seat_row_name": "L",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "L_0",
						"seat_row_name": "L",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "L_0",
						"seat_row_name": "L",
						"seat_number":   "0",
						"seat_type":     0,
						"status":        0},
					{
						"seat_id":       "L_8",
						"seat_row_name": "L",
						"seat_number":   "8",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "L_8",
						"seat_row_name": "L",
						"seat_number":   "8",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "L_9",
						"seat_row_name": "L",
						"seat_number":   "9",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "L_9",
						"seat_row_name": "L",
						"seat_number":   "9",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "L_10",
						"seat_row_name": "L",
						"seat_number":   "10",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "L_10",
						"seat_row_name": "L",
						"seat_number":   "10",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "L_11",
						"seat_row_name": "L",
						"seat_number":   "11",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "L_11",
						"seat_row_name": "L",
						"seat_number":   "11",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "L_12",
						"seat_row_name": "L",
						"seat_number":   "12",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "L_12",
						"seat_row_name": "L",
						"seat_number":   "12",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "L_13",
						"seat_row_name": "L",
						"seat_number":   "13",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "L_13",
						"seat_row_name": "L",
						"seat_number":   "13",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "L_14",
						"seat_row_name": "L",
						"seat_number":   "14",
						"seat_type":     "1",
						"status":        0},
					{
						"seat_id":       "L_14",
						"seat_row_name": "L",
						"seat_number":   "14",
						"seat_type":     "1",
						"status":        0}}}},
		"booked_seats": []string{}}}

// playMoviesList = append(playMoviesList, map[string]string{
// 	"movie_id":     "934",
// 	"imdb_id":      "tt4154664",
// 	"title":        "Captain Marvel",
// 	"genre":        "Action, Adventure",
// 	"language":     "English",
// 	"director":     "Anna Boden, Ryan Fleck",
// 	"producer":     "Victoria Alonso",
// 	"release_date": "2019-03-08",
// 	"cast":         "Brie Larson",
// 	"ranking":      "6.0",
// 	"length":       "124",
// 	"thumbnail":    "https://bookme.pk/custom/upload/marvil_IMDB.jpg"})

// playMoviesList = append(playMoviesList, map[string]string{
// 	"movie_id":     "901",
// 	"imdb_id":      "",
// 	"title":        "3 BAHADUR",
// 	"genre":        "Adventure,  Animation, Family",
// 	"language":     "Urdu",
// 	"director":     "Sharmeen Obaid Chinoy",
// 	"producer":     "Waadi Animations",
// 	"release_date": "2018-12-14",
// 	"cast":         " Mehwish HayatFahad MustafaSarwat GillaniNimra BuchaBehroze Sabzwari",
// 	"ranking":      "0.9",
// 	"length":       "120",
// 	"thumbnail":    "https://bookme.pk/custom/upload/3_Bahadur_RiseWarriors_IMDB.jpeg"})

// playMoviesList = append(playMoviesList, map[string]string{
// 	"movie_id":     "898",
// 	"imdb_id":      "tt1477834",
// 	"title":        "AQUAMAN",
// 	"genre":        "Action, Adventure, Fantasy",
// 	"language":     "English",
// 	"director":     "James Wan",
// 	"producer":     "Peter Safran",
// 	"release_date": "2018-12-21",
// 	"cast":         "Jason Momoa, Amber Heard, Nicole Kidman",
// 	"ranking":      "7.5",
// 	"length":       "143",
// 	"thumbnail":    "https://bookme.pk/custom/upload/Aquaman_IMDB.jpg"})

// playMoviesList = append(playMoviesList, map[string]string{
// 	"movie_id":     "881",
// 	"imdb_id":      "tt1727824",
// 	"title":        "Bohemian Rhapsody",
// 	"genre":        "Drama, Biography  , Music",
// 	"language":     "English",
// 	"director":     "Bryan Singer",
// 	"producer":     "",
// 	"release_date": "2018-11-02",
// 	"cast":         "Rami Malek, Lucy Boynton, Gwilym Lee",
// 	"ranking":      "8.1",
// 	"length":       "134",
// 	"thumbnail":    "https://bookme.pk/custom/upload/Bohemian IMDB.jpg"})

// playMoviesList = append(playMoviesList, map[string]string{
// 	"movie_id":     "855",
// 	"imdb_id":      "",
// 	"title":        "THE DONKEY KING",
// 	"genre":        " Animation",
// 	"language":     "Urdu",
// 	"director":     "Aziz Jindani",
// 	"producer":     "Talisman Studios",
// 	"release_date": "2018-10-13",
// 	"cast":         "Jan Rambo, Ismail Tara, Hina Dilpazeer, Ghulam Mohiuddin, Jawed Sheikh",
// 	"ranking":      "7.2",
// 	"length":       "120",
// 	"thumbnail":    "https://bookme.pk/custom/upload/TDK_IMDB.jpg"})

// playMoviesList = append(playMoviesList, map[string]string{
// 	"movie_id":     "835",
// 	"imdb_id":      "tt8032912",
// 	"title":        "PARWAAZ HAI JUNOON",
// 	"genre":        "Action, Romance, War",
// 	"language":     "Urdu",
// 	"director":     "Haseeb Hasan",
// 	"producer":     "Momina Duraid",
// 	"release_date": "2018-08-22",
// 	"cast":         "Hamza Ali Abbasi, Hania Aamir, Ahad Raza Mir, Shaz Khan, Kubra Khan and others",
// 	"ranking":      "8.5",
// 	"length":       "130",
// 	"thumbnail":    "https://bookme.pk/custom/upload/parwaz_IMDB.jpg"})

// playMoviesList = append(playMoviesList, map[string]string{
// 	"movie_id":     "829",
// 	"imdb_id":      "tt7816386",
// 	"title":        "JAWANI PHIR NAHI ANI 2",
// 	"genre":        "Comedy",
// 	"language":     "Urdu",
// 	"director":     "Nadeem Beyg",
// 	"producer":     "Salman Iqbal,Humayun Saeed,Shahzad NasibJarjees Seja",
// 	"release_date": "2018-08-21",
// 	"cast":         "Mawra Hocane,Kanwaljit Singh,Humayun Saeed",
// 	"ranking":      "8.0",
// 	"length":       "165",
// 	"thumbnail":    "https://bookme.pk/custom/upload/JPNA2_IMDB.jpg"})

// playMoviesList = append(playMoviesList, map[string]string{
// 	"movie_id":     "824",
// 	"imdb_id":      "tt4912910",
// 	"title":        "Mission Impossible Fallout",
// 	"genre":        "Action, Thriller, Adventure",
// 	"language":     "English",
// 	"director":     "Christopher McQuarrie",
// 	"producer":     "Tom Cruise",
// 	"release_date": "2018-07-27",
// 	"cast":         "Tom Cruise,Rebecca Ferguson,Henry Cavill",
// 	"ranking":      "7.8",
// 	"length":       "227",
// 	"thumbnail":    "https://bookme.pk/custom/upload/mif_IMDB.jpg"})
