package main

// var playMoviesList []map[string]interface{}

var playMoviesList = []map[string]interface{}{
	{
		"movie_id":     "934",
		"imdb_id":      "tt4154664",
		"title":        "Captain Marvel",
		"genre":        "Action, Adventure",
		"language":     "English",
		"director":     "Anna Boden, Ryan Fleck",
		"producer":     "Victoria Alonso",
		"release_date": "2019-03-08",
		"cast":         "Brie Larson",
		"ranking":      "6.0",
		"length":       "124",
		"thumbnail":    "https://bookme.pk/custom/upload/marvil_IMDB.jpg"},
	{
		"movie_id":     "901",
		"imdb_id":      "",
		"title":        "3 BAHADUR",
		"genre":        "Adventure,  Animation, Family",
		"language":     "Urdu",
		"director":     "Sharmeen Obaid Chinoy",
		"producer":     "Waadi Animations",
		"release_date": "2018-12-14",
		"cast":         " Mehwish HayatFahad MustafaSarwat GillaniNimra BuchaBehroze Sabzwari",
		"ranking":      "0.9",
		"length":       "120",
		"thumbnail":    "https://bookme.pk/custom/upload/3_Bahadur_RiseWarriors_IMDB.jpeg"}}

var playMovieShowsList = []map[string]interface{}{
	{
		"movie_id":       "942",
		"imdb_id":        "tt5897108",
		"title":          "Project Ghazi",
		"genre":          "Action, Thriller, Sci-Fi",
		"language":       "Urdu",
		"director":       "Nadir Shah",
		"producer":       "Syed Mohammad Ali Raza",
		"release_date":   "2019-03-22",
		"cast":           "Humayun Saeed, Sheheryar Munawar Siddiqui, Syra Shehroz, Adnan Jaffar",
		"ranking":        "8.0",
		"length":         "120",
		"thumbnail":      "https://bookme.pk/custom/upload/PG_IMDB.jpg",
		"music_director": "-",
		"country":        "Pakistan",
		"synopsis":       "Project Ghazi is a superhero movie that evolves around a thread to the project soldiers. Its a story of an advanced soldier project and it spans over a period of 20 years.",
		"details":        "",
		"trailer_link":   "https://bookme.pk/custom/videoupload/PG_Trailer.mp4",
		"date":           "2019-03-08 19:56:33",
		"booking_type":   "0",
		"points":         "0",
		"update_date":    nil,
		"close_date":     nil,
		"status":         "1",
		"shows": []map[string]interface{}{
			{"city_id": "1",
				"city_name":         "Lahore",
				"show_id":           "481862",
				"show_movie_id":     "942",
				"show_cenima_id":    "8888",
				"cinema_name":       "Universal Cinema lahore Emporium Mall",
				"hall_id":           "148",
				"hall_name":         "Screen 3 ",
				"show_date":         "2019-03-29",
				"show_start_time":   "2019-03-29 16:00:00",
				"show_time":         "16:00",
				"ticket_price":      "600",
				"handling_charges":  30,
				"easypaisa_charges": 0,
				"house_full":        "0",
				"eticket":           "1"},
			{"city_id": "2",
				"city_name":         "Karachi",
				"show_id":           "481856",
				"show_movie_id":     "942",
				"show_cenima_id":    "19",
				"cinema_name":       "Atrium Cinema",
				"hall_id":           "62",
				"hall_name":         "Cinema A 2D ",
				"show_date":         "2019-03-30",
				"show_start_time":   "2019-03-30 15:00:00",
				"show_time":         "15:00",
				"ticket_price":      "600",
				"handling_charges":  30,
				"easypaisa_charges": 0,
				"house_full":        "0",
				"eticket":           "1"},
			{"city_id": "3",
				"city_name":         "Islamabad",
				"show_id":           "481858",
				"show_movie_id":     "942",
				"show_cenima_id":    "20",
				"cinema_name":       "Centaurus Cineplex",
				"hall_id":           "68",
				"hall_name":         "Cinema 1 2D ",
				"show_date":         "2019-03-30",
				"show_start_time":   "2019-03-30 14:00:00",
				"show_time":         "14:00",
				"ticket_price":      "600",
				"handling_charges":  30,
				"easypaisa_charges": 0,
				"house_full":        "0",
				"eticket":           "1"}}},

	{
		"movie_id":       "824",
		"imdb_id":        "tt4912910",
		"title":          "Mission Impossible Fallout",
		"genre":          "Action, Thriller, Adventure",
		"language":       "English",
		"director":       "Christopher McQuarrie",
		"producer":       "Tom Cruise",
		"release_date":   "2018-07-27",
		"cast":           "Tom Cruise,Rebecca Ferguson,Henry Cavill",
		"ranking":        "7.8",
		"length":         "227",
		"thumbnail":      "https://bookme.pk/custom/upload/mif_IMDB.jpg",
		"music_director": "Lorne Balfe",
		"country":        "USA",
		"synopsis":       "Ethan Hunt and his IMF team, along with some familiar allies, race against time after a mission gone wrong.",
		"details":        "",
		"trailer_link":   "https://bookme.pk/custom/videoupload/MIF_Trailer.mp4",
		"date":           "2019-03-01 18:58:29",
		"booking_type":   "0",
		"points":         "0",
		"update_date":    "2018-07-23 20:28:37",
		"close_date":     nil,
		"status":         "1",
		"shows": []map[string]interface{}{
			{
				"city_id":           "1",
				"city_name":         "Lahore",
				"show_id":           "480889",
				"show_movie_id":     "824",
				"show_cenima_id":    "8888",
				"cinema_name":       "Universal Cinema lahore Emporium Mall",
				"hall_id":           "149",
				"hall_name":         "Screen 4 Premium B",
				"show_date":         "2019-03-10",
				"show_start_time":   "2019-03-10 17:30:00",
				"show_time":         "17:30",
				"ticket_price":      "700",
				"handling_charges":  35,
				"easypaisa_charges": 0,
				"house_full":        "0",
				"eticket":           "1"},
			{
				"city_id":           "11",
				"city_name":         "Rawalpindi",
				"show_id":           "480788",
				"show_movie_id":     "824",
				"show_cenima_id":    "10009",
				"cinema_name":       "Odeon Cineplex",
				"hall_id":           "203",
				"hall_name":         "Red Hall Vip Box",
				"show_date":         "2019-03-10",
				"show_start_time":   "2019-03-10 19:45:00",
				"show_time":         "19:45",
				"ticket_price":      "3000",
				"handling_charges":  150,
				"easypaisa_charges": 0,
				"house_full":        "0",
				"eticket":           ""}}}}

// playMoviesList = append(playMoviesList, map[string]string{
// 	"movie_id":     "934",
// 	"imdb_id":      "tt4154664",
// 	"title":        "Captain Marvel",
// 	"genre":        "Action, Adventure",
// 	"language":     "English",
// 	"director":     "Anna Boden, Ryan Fleck",
// 	"producer":     "Victoria Alonso",
// 	"release_date": "2019-03-08",
// 	"cast":         "Brie Larson",
// 	"ranking":      "6.0",
// 	"length":       "124",
// 	"thumbnail":    "https://bookme.pk/custom/upload/marvil_IMDB.jpg"})

// playMoviesList = append(playMoviesList, map[string]string{
// 	"movie_id":     "901",
// 	"imdb_id":      "",
// 	"title":        "3 BAHADUR",
// 	"genre":        "Adventure,  Animation, Family",
// 	"language":     "Urdu",
// 	"director":     "Sharmeen Obaid Chinoy",
// 	"producer":     "Waadi Animations",
// 	"release_date": "2018-12-14",
// 	"cast":         " Mehwish HayatFahad MustafaSarwat GillaniNimra BuchaBehroze Sabzwari",
// 	"ranking":      "0.9",
// 	"length":       "120",
// 	"thumbnail":    "https://bookme.pk/custom/upload/3_Bahadur_RiseWarriors_IMDB.jpeg"})

// playMoviesList = append(playMoviesList, map[string]string{
// 	"movie_id":     "898",
// 	"imdb_id":      "tt1477834",
// 	"title":        "AQUAMAN",
// 	"genre":        "Action, Adventure, Fantasy",
// 	"language":     "English",
// 	"director":     "James Wan",
// 	"producer":     "Peter Safran",
// 	"release_date": "2018-12-21",
// 	"cast":         "Jason Momoa, Amber Heard, Nicole Kidman",
// 	"ranking":      "7.5",
// 	"length":       "143",
// 	"thumbnail":    "https://bookme.pk/custom/upload/Aquaman_IMDB.jpg"})

// playMoviesList = append(playMoviesList, map[string]string{
// 	"movie_id":     "881",
// 	"imdb_id":      "tt1727824",
// 	"title":        "Bohemian Rhapsody",
// 	"genre":        "Drama, Biography  , Music",
// 	"language":     "English",
// 	"director":     "Bryan Singer",
// 	"producer":     "",
// 	"release_date": "2018-11-02",
// 	"cast":         "Rami Malek, Lucy Boynton, Gwilym Lee",
// 	"ranking":      "8.1",
// 	"length":       "134",
// 	"thumbnail":    "https://bookme.pk/custom/upload/Bohemian IMDB.jpg"})

// playMoviesList = append(playMoviesList, map[string]string{
// 	"movie_id":     "855",
// 	"imdb_id":      "",
// 	"title":        "THE DONKEY KING",
// 	"genre":        " Animation",
// 	"language":     "Urdu",
// 	"director":     "Aziz Jindani",
// 	"producer":     "Talisman Studios",
// 	"release_date": "2018-10-13",
// 	"cast":         "Jan Rambo, Ismail Tara, Hina Dilpazeer, Ghulam Mohiuddin, Jawed Sheikh",
// 	"ranking":      "7.2",
// 	"length":       "120",
// 	"thumbnail":    "https://bookme.pk/custom/upload/TDK_IMDB.jpg"})

// playMoviesList = append(playMoviesList, map[string]string{
// 	"movie_id":     "835",
// 	"imdb_id":      "tt8032912",
// 	"title":        "PARWAAZ HAI JUNOON",
// 	"genre":        "Action, Romance, War",
// 	"language":     "Urdu",
// 	"director":     "Haseeb Hasan",
// 	"producer":     "Momina Duraid",
// 	"release_date": "2018-08-22",
// 	"cast":         "Hamza Ali Abbasi, Hania Aamir, Ahad Raza Mir, Shaz Khan, Kubra Khan and others",
// 	"ranking":      "8.5",
// 	"length":       "130",
// 	"thumbnail":    "https://bookme.pk/custom/upload/parwaz_IMDB.jpg"})

// playMoviesList = append(playMoviesList, map[string]string{
// 	"movie_id":     "829",
// 	"imdb_id":      "tt7816386",
// 	"title":        "JAWANI PHIR NAHI ANI 2",
// 	"genre":        "Comedy",
// 	"language":     "Urdu",
// 	"director":     "Nadeem Beyg",
// 	"producer":     "Salman Iqbal,Humayun Saeed,Shahzad NasibJarjees Seja",
// 	"release_date": "2018-08-21",
// 	"cast":         "Mawra Hocane,Kanwaljit Singh,Humayun Saeed",
// 	"ranking":      "8.0",
// 	"length":       "165",
// 	"thumbnail":    "https://bookme.pk/custom/upload/JPNA2_IMDB.jpg"})

// playMoviesList = append(playMoviesList, map[string]string{
// 	"movie_id":     "824",
// 	"imdb_id":      "tt4912910",
// 	"title":        "Mission Impossible Fallout",
// 	"genre":        "Action, Thriller, Adventure",
// 	"language":     "English",
// 	"director":     "Christopher McQuarrie",
// 	"producer":     "Tom Cruise",
// 	"release_date": "2018-07-27",
// 	"cast":         "Tom Cruise,Rebecca Ferguson,Henry Cavill",
// 	"ranking":      "7.8",
// 	"length":       "227",
// 	"thumbnail":    "https://bookme.pk/custom/upload/mif_IMDB.jpg"})
